### user signup endpoint
POST http://localhost:3000/v1/user
Content-Type: application/json

{   
"name":"arun pandian",
"company":"company name",
"address":"some address",
"phone":632873737,
"email":"arat@e.com",
"password":"secret123"

}

### user sign in endpoint
POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
    "email":"arat@e.com",
    "password":"secret123"
}